// Parity test runner: executes the browser JS implementation (docs/js) under Node
// on inputs generated by the Python test suite, and writes the results as JSON.
//
// Usage:
//   node js_runner.mjs run   <inputs.json> <outputs.json>
//   node js_runner.mjs score <inputs.json> <outputs.json>

import fs from 'node:fs';

import { Chess } from '../../docs/js/chess.esm.js';
import { ALL_MOVES, mirrorMove, moveIndex, getLegalMovesMask } from '../../docs/js/moves.js';
import { tokenizeBoard, getHistoricalTokens, buildBatchTensor, buildBatchTensorSingleColor, selectSampleIndices } from '../../docs/js/tensor.js';
import { parsePgnToPositions } from '../../docs/js/pgn.js';
import { computeScoreStreaming } from '../../docs/js/scoring.js';

// The browser modules expect window.Chess / window.__moveIndex globals.
globalThis.window = { Chess, __moveIndex: moveIndex };

function boardFromFen(fen) {
  const board = new Chess();
  board.load(fen);
  return board;
}

function runAll(input) {
  const out = {};

  // A. Move vocabulary
  out.allMoves = ALL_MOVES;

  // B. Mirror moves
  out.mirror = {};
  for (const uci of input.mirrorUcis) {
    out.mirror[uci] = mirrorMove(uci);
  }

  // C. Move indices for every legal move of each position
  // D. Board tokenizations
  // E. Legal move masks
  out.moveIndex = {};
  out.tokenize = {};
  out.legalMask = {};
  for (const fen of input.fens) {
    const board = boardFromFen(fen);
    const isBlackTurn = board.turn() === 'b';

    const indexMap = {};
    for (const move of board.moves({ verbose: true })) {
      const uci = move.from + move.to + (move.promotion || '');
      indexMap[uci] = moveIndex(uci, isBlackTurn);
    }
    out.moveIndex[fen] = indexMap;

    out.tokenize[fen] = Array.from(tokenizeBoard(board));
    out.legalMask[fen] = Array.from(getLegalMovesMask(board, isBlackTurn));
  }

  // F. Historical tokens
  out.historical = (input.histories || []).map((h) => {
    const history = h.fens.map((fen) => tokenizeBoard(boardFromFen(fen)));
    return Array.from(getHistoricalTokens(history));
  });

  // G. Batch tensors
  out.batches = (input.games || []).map((game) => {
    const parsed = parsePgnToPositions(game.pgn);
    if (!parsed) return null;
    const batch = buildBatchTensor(parsed.positions, game.eloValues, 0);
    if (!batch) return null;
    return {
      tokens: Array.from(batch.tokens),
      selfElos: Array.from(batch.selfElos),
      oppoElos: Array.from(batch.oppoElos),
      humanMoves: Array.from(batch.humanMoves),
      legalMasks: Array.from(batch.legalMasks),
      nPositions: batch.nPositions,
      nElos: batch.nElos,
    };
  });

  // G2. Single-color batch tensors (per-color refinement path)
  out.singleColorBatches = (input.singleColorGames || []).map((game) => {
    const parsed = parsePgnToPositions(game.pgn);
    if (!parsed) return null;
    const batch = buildBatchTensorSingleColor(
      parsed.positions,
      game.eloValues,
      game.colorIsWhite,
      game.opponentElo,
      0,
    );
    if (!batch) return null;
    return {
      tokens: Array.from(batch.tokens),
      selfElos: Array.from(batch.selfElos),
      oppoElos: Array.from(batch.oppoElos),
      humanMoves: Array.from(batch.humanMoves),
      legalMasks: Array.from(batch.legalMasks),
      nPositions: batch.nPositions,
      nElos: batch.nElos,
    };
  });

  // Sampling index selection
  out.sampling = (input.samplingCases || []).map((c) =>
    Array.from(selectSampleIndices(c.totalMoves, c.nSample))
  );

  // I. PGN parsing
  out.pgns = (input.pgns || []).map((pgn) => {
    try {
      const parsed = parsePgnToPositions(pgn);
      if (!parsed) return null;
      return {
        positions: parsed.positions.map((pos) => ({
          moveUci: pos.moveUci,
          isWhiteTurn: pos.isWhiteTurn,
          clkLeftBefore: pos.clkLeftBefore,
          clkPonder: pos.clkPonder,
        })),
        nMoves: parsed.nMoves,
      };
    } catch (err) {
      return { error: String(err && err.message ? err.message : err) };
    }
  });

  return out;
}

function scoreOnly(input) {
  const scores = computeScoreStreaming(
    Float64Array.from(input.logits),
    Int32Array.from(input.humanMoves),
    Uint8Array.from(input.legalMasks),
    input.nPos,
    input.nElo,
  );
  return { scores: Array.from(scores) };
}

const [, , mode, inPath, outPath] = process.argv;
if (!mode || !inPath || !outPath) {
  console.error('usage: node js_runner.mjs <run|score> <inputs.json> <outputs.json>');
  process.exit(2);
}

const input = JSON.parse(fs.readFileSync(inPath, 'utf8'));
const output = mode === 'run' ? runAll(input) : scoreOnly(input);
fs.writeFileSync(outPath, JSON.stringify(output));
console.error(`js_runner: ${mode} ok`);
